# Generated by Django 2.2 on 2019-05-24 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apply', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apply',
            name='body',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='apply',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='apply',
            name='file',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='apply',
            name='isFinal',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='apply',
            name='major',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='apply',
            name='phone',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='apply',
            name='student_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='apply',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
