# Generated by Django 2.1.8 on 2019-05-24 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apply', '0002_auto_20190524_1629'),
        ('apply', '0002_auto_20190524_1706'),
    ]

    operations = [
    ]
