# Generated by Django 2.2.1 on 2019-05-29 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='hits',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='board',
            name='solved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='board',
            name='writer',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
