# Generated by Django 2.2 on 2019-05-30 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0002_board_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
