# Generated by Django 2.2.1 on 2019-05-30 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0005_auto_20190527_0035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='board',
            field=models.ForeignKey(null=True, on_delete=True, related_name='comments', to='question.Board'),
        ),
    ]
