# Generated by Django 2.2.1 on 2019-05-21 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='file',
            field=models.FileField(default=-1.0, upload_to='document/'),
            preserve_default=False,
        ),
    ]
