# Generated by Django 2.2.1 on 2019-05-18 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tip', '0002_tip_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadFileModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(default='')),
                ('file', models.FileField(null=True, upload_to='')),
            ],
        ),
        migrations.RemoveField(
            model_name='tip',
            name='photo',
        ),
    ]
