# Generated by Django 2.2.1 on 2019-05-18 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tip', '0003_auto_20190518_0023'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UploadFileModel',
        ),
        migrations.AddField(
            model_name='tip',
            name='file',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
