# Generated by Django 2.2.1 on 2019-05-18 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tip', '0004_auto_20190518_0235'),
    ]

    operations = [
        migrations.AddField(
            model_name='tip',
            name='hit',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
